"""Add framework_agreemet model

Revision ID: 155067bddb09
Revises: 710
Create Date: 2016-08-25 15:10:22.541037

"""

# revision identifiers, used by Alembic.
revision = '720'
down_revision = '710'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('agreement_returned_at', sa.DateTime(), nullable=True),
    sa.Column('countersigned_at', sa.DateTime(), nullable=True),
    sa.Column('signature_page_url', sa.String(), nullable=True),
    sa.Column('countersignature_page_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_agreements')
    ### end Alembic commands ###
