"""add_agreement_details_to_framework_agreement

Revision ID: 2e57f147de8a
Revises: 720
Create Date: 2016-08-25 15:38:07.740525

"""

# revision identifiers, used by Alembic.
revision = '730'
down_revision = '720'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_agreements', sa.Column('agreement_details', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_agreements', 'agreement_details')
    ### end Alembic commands ###
